### ISSUE TITLE
Class 'Curl' not found

### ISSUE THREAD

**Issue by KHN190** [kulisu/metasploit-pro-trial-grabber#13]
I got a problem loading class Curl, which should be a problem with [php-curl-lib](https://github.com/php-curl-class/php-curl-class):

    [+] defining the pre-required constants .. DONE !
    [+] loading the 3rd-party libraries .. DONE !
    [+] creating all classes' instance .. PHP Fatal error:  Class 'Curl' not found in /path/metasploit-pro-trial-grabber/execute.php on line 96

**Comment by kulisu** [comment]
Hi @KHN190,

yap, please use `php-curl-class 2.0.0` and this error should not occur again :smiley:

Chris
